name = "ITensorAGP"
uuid = "50ba78bc-899b-4cea-8ce4-e2d64a1bd294"
authors = ["Hyeongjin Kim <hkim12@bu.edu>, Matthew Fishman <mfishman@flatironinstitute.org>"]
version = "1.0.0-DEV"

[deps]
ITensorTDVP = "25707e16-a4db-4a07-99d9-4d67b7af0342"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
ITensorTDVP = "0.2"
ITensors = "0.3.60"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
