name = "ITensorAGP"
uuid = "50ba78bc-899b-4cea-8ce4-e2d64a1bd294"
authors = ["Hyeongjin Kim <hkim12@bu.edu>, Matthew Fishman <mfishman@flatironinstitute.org>"]
version = "1.0.0-DEV"

[deps]
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
ITensors = "0.3.60, 0.4, 0.5, 0.6"
LinearAlgebra = "1.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
