name = "ITensorAGP"
uuid = "50ba78bc-899b-4cea-8ce4-e2d64a1bd294"
authors = ["Hyeongjin Kim <hkim12@bu.edu>, Matthew Fishman <mfishman@flatironinstitute.org>"]
version = "1.0.0-DEV"

[deps]
ITensorTDVP = "25707e16-a4db-4a07-99d9-4d67b7af0342"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"

[compat]
julia = "1.6"
ITensors = "0.3.20"
ITensorTDVP = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
