name = "ITensorAGP"
uuid = "50ba78bc-899b-4cea-8ce4-e2d64a1bd294"
authors = ["Hyeongjin Kim and Matthew Fishman"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
